models/brand.py
from database import db


class Brand(db.Model):
    """
    This class represents a Toner object.

    Attributes:
        id (int): The unique identifier for the color.
        name (str): The name of the brand.

    Methods:
        to_dict(): Converts the toner object to a dictionary representation.
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))

    def to_dict(self):
        return {"id": self.id, "name": self.name}

forms/brand.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField


class BrandForm(FlaskForm):
    name = StringField('Name')

    def to_dict(self):
        # Return a dict but without submit
        return {key: value for key, value in self.data.items() if key != 'submit' and key != 'csrf_token'}

views/brand.py
from flask import Blueprint, render_template, flash, redirect, url_for

from forms.brand import BrandForm
from services.brand import BrandService

brand_views = Blueprint('brand_views', __name__, url_prefix='/brands')


@brand_views.route('/', methods=['GET'])
def show_all_brands():
    brands = BrandService.get_all()
    return render_template('brand/list.html', brands=brands)


@brand_views.route('/<int:brand_id>', methods=['GET'])
def show_brand(brand_id):
    brand = BrandService.get_by_id(brand_id)
    return render_template('brand/details.html', brand=brand)


@brand_views.route('/new', methods=['GET', 'POST'])
def new_brand():
    form = BrandForm()
    if form.validate_on_submit():
        BrandService.create(form.to_dict())
        flash('Brand {} has been added!'.format(form.name.data))
        return redirect(url_for('brand_views.show_all_brands'))
    return render_template('brand/new.html', form=form)


@brand_views.route('/<int:brand_id>/delete', methods=['POST'])
def delete_brand(brand_id):
    # access the id from posted data instead of a form

    if brand_id is not None:
        deleted_brand = BrandService.delete(brand_id)
        if deleted_brand:
            flash(f'Brand {deleted_brand.name} has been deleted!')
            return redirect(url_for('brand_views.show_all_brands'))

    flash('An error has occurred. Deletion unsuccessful.')
    return redirect(url_for('brand_views.show_all_brands'))

templates/brand/details.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title">{{ brand.name }}</h1>
        </div>
    </section>
{% endblock %}

templates/brand/list.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title is-3">Marken</h1>
            <h2 class="title is-5"><a href="{{ url_for('brand_views.new_brand') }}" class="button is-primary">Neu</a>
            </h2>
            {% for brand in brands %}
                <div class="box">
                    <h2 class="title is-5"><a
                            href="{{ url_for('brand_views.show_brand', brand_id=brand.id) }}">{{ brand.name }}</a></h2>
                    <form action="{{ brand.id }}/delete" method="POST">
                        <!-- Hidden input field to submit the id -->
                        <input type="hidden" name="id" value="{{ brand.id }}">
                        <button class="button is-danger mt-2" type="submit">
                            <i class="fas fa-trash"></i>
                        </button>
                    </form>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/brand/new.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title">Neue Marke</h1>
            <form method="POST">
                {% set form_fields = ['name'] %}
                {{ form.hidden_tag() }}
                {% for field in form_fields %}
                    <div class="field">
                        <label class="label">{{ field.title() }}</label>
                        <div class="control">
                          <!-- Adding Bulma's input class -->
                          {{ form[field](class="input") }}
                        </div>
                    </div>
                {% endfor %}
                <div class="field">
                    <div class="control">
                        <!-- Adding Bulma's button class -->
                        <input type="submit" value="Erstellen" class="button is-primary">
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}