models/drum.py
from database import db


class Drum(db.Model):
    """
    This class represents a Drum object.

    Attributes:
        id (int): The unique identifier for the drum.
        brand (str): The brand of the drum.
        name (str): The name of the drum.
        color (str): The color of the drum.
        scope_of_delivery (str): The scope of delivery for the drum.
        cartridge_no (str): The cartridge number of the drum.
        compatible_printers (str): The compatible printers for the drum.
        max_printable_pages (int): The maximum number of printable pages for the drum.

    Methods:
        to_dict(): Converts the drum object to a dictionary representation.
    """
    id = db.Column(db.Integer, primary_key=True)
    brand = db.Column(db.String(50))
    name = db.Column(db.String(50))
    color = db.Column(db.String(50))
    scope_of_delivery = db.Column(db.String(100))
    cartridge_no = db.Column(db.String(50))
    cartridge_size = db.Column(db.String(2))
    cartridge_type = db.Column(db.String(50))
    compatible_printers = db.Column(db.String(200))
    max_printable_pages = db.Column(db.Integer)

    def to_dict(self):
        return {"id": self.id, "brand": self.brand, "name": self.name, "color": self.color,
                "scope_of_delivery": self.scope_of_delivery, "cartridge_no": self.cartridge_no,
                "cartridge_size": self.cartridge_size, "compatible_printers": self.compatible_printers,
                "max_printable_pages": self.max_printable_pages}

views/toner.py
from flask import render_template, Blueprint, flash, redirect, url_for, request

from forms.toner import TonerForm
from services.toner import TonerService

toner_views = Blueprint('toner_views', __name__, url_prefix='/toners')


@toner_views.route('/', methods=['GET'])
def show_all_toners():
    toners = TonerService.get_all()
    return render_template('toner/list.html', toners=toners)


@toner_views.route('/<int:id>', methods=['GET'])
def show_toner(id):
    toner = TonerService.get_by_id(id)
    return render_template('toner/details.html', toner=toner)


@toner_views.route('/new', methods=['GET', 'POST'])
def new_toner():
    form = TonerForm()
    if form.validate_on_submit():
        TonerService.create(form.to_dict())
        flash('Toner {} has been added!'.format(form.name.data))
        return redirect(url_for('toner_views.show_all_toners'))
    return render_template('toner/new.html', form=form)


@toner_views.route('/delete', methods=['POST'])
def delete_toner():
    # access the id from posted data instead of a form
    toner_id = request.form.get('id')

    if toner_id is not None:
        deleted_toner = TonerService.delete(toner_id)
        if deleted_toner:
            flash(f'Toner {deleted_toner.name} has been deleted!')
            return redirect(url_for('toner_views.show_all_toners'))

    flash('An error has occurred. Deletion unsuccessful.')
    return redirect(url_for('toner_views.show_all_toners'))

templates/drum/details.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title">{{ color.name }}</h1>
            <p>Hex: {{ toner.hex }}</p>
        </div>
    </section>
{% endblock %}

templates/drum/list.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title is-3">All Toners</h1>
            <h2 class="title is-5"><a href="{{ url_for('toner_views.new_toner') }}" class="button is-primary">New</a></h2>
            {% for toner in toners %}
            <div class="box">
                <h2 class="title is-5"><a href="{{ url_for('toner_views.show_toner', id=toner.id) }}">{{ toner.name }}</a></h2>
                <p>Brand: {{ toner.brand }}</p>
                <p>Color: {{ toner.color }}</p>
            </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/drum/new.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title">New Color</h1>
            <form method="POST">
                {% set form_fields = ['name', 'hex'] %}
                {{ form.hidden_tag() }}
                {% for field in form_fields %}
                    <div class="field">
                        <label class="label">{{ field.title() }}</label>
                        <div class="control">
                          <!-- Adding Bulma's input class -->
                          {{ form[field](class="input") }}
                        </div>
                    </div>
                {% endfor %}
                <div class="field">
                    <div class="control">
                        <!-- Adding Bulma's button class -->
                        <input type="submit" value="Submit" class="button is-primary">
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}