models/color.py
from database import db


class Color(db.Model):
    """
    This class represents a Toner object.

    Attributes:
        id (int): The unique identifier for the color.
        name (str): The name of the color.

    Methods:
        to_dict(): Converts the toner object to a dictionary representation.
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))

    def to_dict(self):
        return {"id": self.id, "name": self.name}

forms/color.py
from flask_wtf import FlaskForm
from wtforms import StringField


class ColorForm(FlaskForm):
    name = StringField('Name')

    def to_dict(self):
        # Return a dict but without submit
        return {key: value for key, value in self.data.items() if key != 'submit' and key != 'csrf_token'}

views/color.py
from flask import Blueprint, render_template, flash, redirect, url_for

from forms.color import ColorForm
from services.color import ColorService

color_views = Blueprint('color_views', __name__, url_prefix='/colors')


@color_views.route('/', methods=['GET'])
def show_all_colors():
    colors = ColorService.get_all()
    return render_template('color/list.html', colors=colors)


@color_views.route('/<int:color_id>', methods=['GET'])
def show_color(color_id):
    color = ColorService.get_by_id(color_id)
    return render_template('color/details.html', color=color)


@color_views.route('/new', methods=['GET', 'POST'])
def new_color():
    form = ColorForm()
    if form.validate_on_submit():
        ColorService.create(form.to_dict())
        flash('Toner {} has been added!'.format(form.name.data))
        return redirect(url_for('color_views.show_all_colors'))
    return render_template('color/new.html', form=form)


@color_views.route('/<int:color_id>/delete', methods=['POST'])
def delete_color(color_id):
    # access the id from posted data instead of a form
    if color_id is not None:
        deleted_color = ColorService.delete(color_id)
        if deleted_color:
            flash(f'Brand {deleted_color.name} has been deleted!')
            return redirect(url_for('color_views.show_all_colors'))

    flash('An error has occurred. Deletion unsuccessful.')
    return redirect(url_for('color_views.show_all_colors'))

templates/color/details.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title">{{ color.name }}</h1>
        </div>
    </section>
{% endblock %}

templates/color/list.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <nav class="navbar" role="navigation" aria-label="main navigation">
                <div class="navbar-brand">
                    <div class="navbar-item">
                        <h1 class="title is-3">Farben</h1>
                    </div>
                </div>

                <div id="navbarBasicExample" class="navbar-menu">
                    <div class="navbar-start">
                        <!-- Items here... -->
                    </div>

                    <div class="navbar-end">
                        <div class="navbar-item">
                            <div class="buttons">
                                <a href="{{ url_for('color_views.new_color') }}" class="button is-primary">Neu</a>
                                <a href="{{ url_for('color_views.new_color') }}" class="button is-secondary">Upload</a>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="columns is-multiline">
                {% for color in colors %}
                    <div class="column is-one-quarter">
                        <div class="card">
                            <header class="card-header">
                                <p class="card-header-title">
                                    <a href="{{ url_for('color_views.show_color', color_id=color.id) }}">{{ color.name }}</a>
                                </p>
                            </header>
                            <footer class="card-footer">
                                <form action="{{ color.id }}/delete" method="POST">
                                    <!-- Hidden input field to submit the id -->
                                    <input type="hidden" name="color_id" value="{{ color.id }}">
                                    <button class="card-footer-item has-text-danger" type="submit">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                            </footer>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/color/new.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title">Neue Farbe</h1>
            <form method="POST">
                {% set form_fields = ['name'] %}
                {{ form.hidden_tag() }}
                {% for field in form_fields %}
                    <div class="field">
                        <label class="label">{{ field.title() }}</label>
                        <div class="control">
                          <!-- Adding Bulma's input class -->
                          {{ form[field](class="input") }}
                        </div>
                    </div>
                {% endfor %}
                <div class="field">
                    <div class="control">
                        <!-- Adding Bulma's button class -->
                        <input type="submit" value="Erstellen" class="button is-primary">
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

templates/color/upload.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title">Upload color</h1>
            <form action="" method="post" enctype="multipart/form-data">
                <label for="csvfile">Select csv file:</label>
                <input type="file" id="csvfile" name="csvfile" accept=".csv"><br>
                <input type="submit" value="Upload">
            </form>
        </div>
    </section>
{% endblock %}